### ISSUE TITLE
Scheduled commit of empty.txt file

### ISSUE THREAD

**Issue by danimtb** [raulperula/raulperula.github.io#1]
This repo seems to have an issue with an automatic scheduled routine of an _empty.txt_ file being deleted and restored every single day at same hours.

Be aware **this can never be considered** as a contribution to opensource projects as you state in your personal website.

Please, address this issue as soon as posible as some people may think you are really contributing to software projects generating this fake github activity.

**Comment by raulperula** [comment]
Thanks for noticing.

That commit is a watchdog that I implemented to be sure the website is alive in my server. There is not a contribution but only a security check.
